version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install -g @angular/cli
      - npm install

  build:
    commands:
      - ng test --watch=false --browsers=ChromeHeadless
      - npm run build

artifacts:
  files:
    - "**/*"
  base-directory: dist/angular-aws-auth/browser
